name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Замените на имя вашей основной ветки

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build # Замените эту команду, если у вас другая команда для сборки проекта

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout --orphan gh-pages
          git rm -rf .
          mv dist/* .
          rmdir dist
          git add -A
          git commit -m "Deploy to GitHub Pages"
          git branch -D main
          git branch -m main
          git push -f origin main
